2016-03-27 04:02:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ãƒ¡ã‚½ãƒƒãƒ‰ã�¯ã‚¯ã‚¨ãƒªã�—ã�‹ã‚µãƒ�ãƒ¼ãƒˆã�—ã�¦ã�„ã�¾ã�›ã‚“ã€‚executeQueryã�®ã�‹ã‚�ã‚Šã�«ã€�excecuteã€�ã�¾ã�Ÿã�¯executeUpdateã‚’ä½¿ç”¨ã�—ã�¦ã��ã� ã�•ã�„
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
 [90002-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Prepared.query(Prepared.java:212)
	at org.h2.command.CommandContainer.query(CommandContainer.java:110)
	at org.h2.command.Command.executeQuery(Command.java:201)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:110)
	at batch.BATCH001.execute(BATCH001.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at main.Main.main(Main.java:52)
2016-03-27 04:04:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ãƒ†ãƒ¼ãƒ–ãƒ« "MEMBER" ã�¯ã�™ã�§ã�«å­˜åœ¨ã�—ã�¾ã�™
Table "MEMBER" already exists; SQL statement:
create table member(name varchar); [42101-191]
2016-03-27 04:14:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: åˆ— "NAME" ã�Œè¦‹ã�¤ã�‹ã‚Šã�¾ã�›ã‚“
Column "NAME" not found; SQL statement:
insert into member values(name=?) [42122-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at batch.BATCH001.execute(BATCH001.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at main.Main.main(Main.java:51)
2016-03-27 04:34:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: åˆ— "NAME" ã�Œè¦‹ã�¤ã�‹ã‚Šã�¾ã�›ã‚“
Column "NAME" not found; SQL statement:
insert into member values(name=?) [42122-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at batch.BATCH001.execute(BATCH001.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at main.Main.main(Main.java:51)
2016-03-27 04:42:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: åˆ— "NAME" ã�Œè¦‹ã�¤ã�‹ã‚Šã�¾ã�›ã‚“
Column "NAME" not found; SQL statement:
insert into member values(name=?) [42122-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at batch.BATCH001.execute(BATCH001.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at main.Main.main(Main.java:51)
2016-03-27 04:43:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: åˆ— "NAME" ã�Œè¦‹ã�¤ã�‹ã‚Šã�¾ã�›ã‚“
Column "NAME" not found; SQL statement:
insert into member values(name=?) [42122-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at batch.BATCH001.execute(BATCH001.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at main.Main.main(Main.java:51)
2016-03-29 17:48:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ "#1" ã�Œã‚»ãƒƒãƒˆã�•ã‚Œã�¦ã�„ã�¾ã�›ã‚“
Parameter "#1" is not set; SQL statement:
insert into member(name) values(?) [90012-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.Parameter.checkSet(Parameter.java:81)
	at org.h2.command.Prepared.checkParameters(Prepared.java:164)
	at org.h2.command.CommandContainer.update(CommandContainer.java:97)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:201)
	at db.PreparedStatementObserver.execute(PreparedStatementObserver.java:90)
	at db.OzeDAO.execute(OzeDAO.java:71)
	at batch.BATCH001.execute(BATCH001.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Interceptor.AppInterceptor.invoke(AppInterceptor.java:42)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at batch.BatchAction.execute(BatchAction.java:44)
	at batch.BatchAction.execute(BatchAction.java:61)
	at batch.AbstractBatchAction.batchStart(AbstractBatchAction.java:76)
	at main.Main.main(Main.java:14)
2016-03-29 17:56:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿ "#1" ã�Œã‚»ãƒƒãƒˆã�•ã‚Œã�¦ã�„ã�¾ã�›ã‚“
Parameter "#1" is not set; SQL statement:
insert into member(name) values(?) [90012-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.Parameter.checkSet(Parameter.java:81)
	at org.h2.command.Prepared.checkParameters(Prepared.java:164)
	at org.h2.command.CommandContainer.update(CommandContainer.java:97)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:201)
	at db.PreparedStatementObserver.execute(PreparedStatementObserver.java:91)
	at db.OzeDAO.execute(OzeDAO.java:71)
	at batch.BATCH001.execute(BATCH001.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Interceptor.AppInterceptor.invoke(AppInterceptor.java:42)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at batch.BatchAction.execute(BatchAction.java:44)
	at batch.BatchAction.execute(BatchAction.java:61)
	at batch.AbstractBatchAction.batchStart(AbstractBatchAction.java:76)
	at main.Main.main(Main.java:14)
2016-03-29 18:31:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: ãƒ¡ã‚½ãƒƒãƒ‰ã�¯ã‚¯ã‚¨ãƒªã�—ã�‹ã‚µãƒ�ãƒ¼ãƒˆã�—ã�¦ã�„ã�¾ã�›ã‚“ã€‚executeQueryã�®ã�‹ã‚�ã‚Šã�«ã€�excecuteã€�ã�¾ã�Ÿã�¯executeUpdateã‚’ä½¿ç”¨ã�—ã�¦ã��ã� ã�•ã�„
Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
drop table member; create table if not exists member(name varchar(50)); [90002-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Prepared.query(Prepared.java:212)
	at org.h2.command.CommandContainer.query(CommandContainer.java:110)
	at org.h2.command.CommandList.query(CommandList.java:54)
	at org.h2.command.Command.executeQuery(Command.java:201)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:110)
	at db.PreparedStatementObserver.execute(PreparedStatementObserver.java:85)
	at db.OzeDAO.selectQuery(OzeDAO.java:244)
	at db.OzeDAO.selectSql(OzeDAO.java:170)
	at batch.BATCH001.execute(BATCH001.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Interceptor.AppInterceptor.invoke(AppInterceptor.java:42)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at batch.BatchAction.execute(BatchAction.java:46)
	at batch.BatchAction.execute(BatchAction.java:63)
	at batch.AbstractBatchAction.batchStart(AbstractBatchAction.java:76)
	at main.Main.main(Main.java:16)
2016-03-29 18:37:08 database: flush
org.h2.message.DbException: ä¸€èˆ¬ã‚¨ãƒ©ãƒ¼: "java.lang.IllegalStateException: The file is locked: nio:/Users/Mac/Documents/workspace/Batchan/db/mydb.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/Mac/Documents/workspace/Batchan/db/mydb.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2460)
	at org.h2.engine.Database.open(Database.java:692)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at db.OzeDAO.setConnection(OzeDAO.java:51)
	at db.OzeDAO.<init>(OzeDAO.java:30)
	at batch.BATCH001.execute(BATCH001.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Interceptor.AppInterceptor.invoke(AppInterceptor.java:42)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at batch.BatchAction.execute(BatchAction.java:46)
	at batch.BatchAction.execute(BatchAction.java:63)
	at batch.AbstractBatchAction.batchStart(AbstractBatchAction.java:76)
	at main.Main.main(Main.java:16)
Caused by: org.h2.jdbc.JdbcSQLException: ä¸€èˆ¬ã‚¨ãƒ©ãƒ¼: "java.lang.IllegalStateException: The file is locked: nio:/Users/Mac/Documents/workspace/Batchan/db/mydb.mv.db [1.4.191/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/Mac/Documents/workspace/Batchan/db/mydb.mv.db [1.4.191/7]" [50000-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/Mac/Documents/workspace/Batchan/db/mydb.mv.db [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 31 more
